### ISSUE TITLE
Generate navigation in components.nav-main.html

### ISSUE THREAD

**Issue by Dietr** [getchopstick/chopstick-boilerplate#127]
I have been using the following snippet which makes it easier to automatically generate the site navigation according to some variables set in the _config.yml

```yml
# Navigation variables
navigation:
  - title: page
    url: /page
  - title: blog
    url: /blog
  - title: contact
    url: /contact
```
```html
<ul class="o-list-inline">
    <!-- Manually define homepage link -->
    <li class="o-list-inline__item{% if page.section == "home" %} is-active{% endif %}">
      <a href="{{ "/" | prepend: site.baseurl }}">Home</a>
    </li>

    <!-- Define your site navigation in _config.yml -->
    {% for item in site.navigation %}
    <li class="o-list-inline__item{% if page.url contains item.url %} is-active{% endif %}">
      <a href="{{ item.url | prepend: site.baseurl }}">{{ item.title | capitalize }}</a>
    </li>
    {% endfor %}
</ul>
```

Any thoughts on this?
