### ISSUE TITLE
Use Jekyll for .scss > .css processing

### ISSUE THREAD

**Issue by Dietr** [getchopstick/chopstick-boilerplate#131]
Because we use a gulp task to process the sass, you have to commit the generated CSS in order to host chopstick boilerplate on github pages. This seems a bit complicated and I see no real reason (except maybe minification and sourcemaps) why we should use a gulp task for this.

Jekyll supports Sass: https://jekyllrb.com/docs/assets/ 
Autoprefixer is also not a problem if we use the octopress plugin.

See config example below:
```

sass:
  sass_dir: _scss
  style: compressed
gems:
  - octopress-autoprefixer
```
